### ISSUE TITLE
Plizzzz add scrolloverflow option!!!

### ISSUE THREAD

**Issue by supervueman** [river-lee/vue-fullpage#5]

**Comment by NikolasMelui** [comment]
Yes yes yes plz add this sheet i realy so tired of it!!!!!!

**Comment by abel-oye** [comment]
Can you describe the scene? Scroll overflow I'm implementing through CSS

**Comment by NikolasMelui** [comment]
@river-lee And it's working absolutely correct, but not on the IOS... And we don't know why!
We can give you full access to our test-container on cloud9 service  so you can see what the problem is!
And after that we can call by skype and try to resolve the problem together. Ok?)
Write to me on email ;-)
slak@samaradom.ru

**Comment by abel-oye** [comment]
See if your problem is solved?

**Comment by NikolasMelui** [comment]
We try it - on the iphone5 and ipad still working bad. On iphone4 all is good.
It scroll down to the end but when you try to scroll it up from bottom - it stuck.
Try this to see what is the problem.
[Our container](http://tattoo-13-opg-cloned-webpackmen.c9users.io:8080/)

**Comment by NikolasMelui** [comment]
Look at this code - we add come between comments "code start" and "code end".
[fullpage_js.zip](https://github.com/river-lee/vue-fullpage/files/1447256/fullpage_js.zip)
